# Generated by Django 4.2.16 on 2024-10-30 05:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版社')),
                ('publish_date', models.DateField()),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('language', models.CharField(default='ja', max_length=10)),
                ('crated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
