# Generated by Django 4.2.16 on 2024-10-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0003_remove_book_price_remove_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=False, upload_to='image/', verbose_name='表紙'),
        ),
    ]
