# Generated by Django 4.2.16 on 2024-11-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
