# Generated by Django 4.2.16 on 2024-11-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0007_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='表紙'),
        ),
    ]
