# Generated by Django 4.2.16 on 2024-11-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0009_book_price_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='表紙'),
        ),
    ]
