# Generated by Django 4.2.16 on 2024-10-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.ImageField(default='icon/kkrn_icon_user_1.png', upload_to='icon/', verbose_name='アイコン'),
        ),
    ]
