# Generated by Django 4.2.16 on 2024-11-02 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emailアドレス', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='ユーザー名'),
        ),
    ]
