FROM node:18-slim

RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /libra-front
COPY ./libra-front/package*.json ./
RUN npm install 
COPY ./libra-front/ .
EXPOSE 8080
CMD [ "npm", "run", "serve" ]