services: 
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 3
    volumes:
      - ./backend:/backend
      - ./backend/staticfiles:/backend/staticfiles
    environment:
      # - SECRET_KEY=django-insecure-eya)b9v_e$x4&=r@99f@nk&*=w@-u!ohs9xgqb^*&==xp3_2wi
      DJANGO_SETTINGS_MODULE: config.settings
      ## ローカル環境時のホスト
      DJANGO_ALLOWED_HOSTS: localhost
      DATABASE_URL: mysql://takato:0605@db:3306/bookstore
      DATABASE_HOST: db
      DATABASE_NAME: bookstore
      DATABASE_USER: takato
      DATABASE_PASSWORD: 0605
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django-api-site
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend
    command: npm run serve
    volumes:
      - ./frontend/libra-front:/backend/libra-front
    ports:
      - "8080:8080"
    networks:
      - django-api-site

  db:
    image: mysql:8.0
    container_name:  db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 20050605
      MYSQL_DATABASE: bookstore
      MYSQL_USER: takato
      MYSQL_PASSWORD: 0605
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - django-api-site
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/staticfiles:/backend/staticfiles
      - ./frontend/libra-front/dist:/usr/share/nginx/html 
    depends_on:
      - backend
      - frontend
    networks:
      - django-api-site
volumes:
  mysql_data:
networks:
  django-api-site:
    driver: bridge
