# FROM node:18-alpine
# WORKDIR /vue
# COPY ./frontend /vue
# RUN npm install && npm run build

# # buildディレクトリをNginxにコピーする準備
# CMD ["sh", "-c", "cp -r dist/* /usr/share/nginx/html"]
FROM node:18-alpine

WORKDIR /vue
COPY ./frontend /vue
RUN npm install

CMD ["npm", "run", "dev"]