FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /backend
COPY . /backend/
COPY requirements.txt /backend/
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt

CMD [ "gunicorn", "config.wagi.application", "--bind", "0.0.0.0:8000" ]